services:
  postgres:
    container_name: postgres-sql-emocare
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: emocare
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - emocare
    restart: unless-stopped

networks:
  emocare:
    driver: bridge

volumes:
  postgres:
    driver: local
